### ISSUE TITLE
Migrate to OpenJDK due to Oracle Java License Change?

### ISSUE THREAD

**Issue by sbondorf** [NetCal/DiscoDNC#45]
Oracle is changing their Java license terms with Java 11. I tried reading up, but I still don't know if we are affected by this change or not. Therefore, I suggest to stay on Java 10 as long as possible and to explore the possibility to switch to OpenJDK.

What raises my concerns is that, if I understood correctly, using their JVM is not necessarily free anymore. Yet, I am not certain if / how the terms "commercial" and "in production" apply to us.
This is due to the academic workflow: We make use of the JVM to create evaluation results, write a scientific paper about them, and hope for acceptance at a conference or in a journal. Upon acceptance, we usually have to sign over the copyright to the publisher (IEEE, ACM, Springer, etc.) and they commercialize our work as downloads from their repositories are not free of charge.
In the future (Java 11+), do I have to use OpenJDK for research? I don't know ... At the moment, it seems safer to me to make the switch to OpenJDK.

**Comment by paulnikolaus** [comment]
I tried OpenJDK (downloaded at [http://jdk.java.net/10/](url)) for my own project and didn't encounter any issues so far.  On macOS, It has the same folder structure as the Oracle version per default. Basically, I just swapped folder without further ado.

**Comment by matyesz** [comment]
Should work without any problems, API is the same, performance I do not know. I read through the new licensing model for Oracle it will prohibit all usage above JDK8. In my opinion we do not have to change pom.xml for this as build environment depends on the environment and not the maven.

**Comment by paulnikolaus** [comment]
https://blog.joda.org/2018/08/java-is-still-available-at-zero-cost.html?m=1

"But in reality, it is now irrelevant as to whether Oracle JDK is $free to download or not. That is because from Java 11, developers can treat Oracle JDK and OpenJDK as being equivalent. It is no longer appropriate or correct to consider the OpenJDK build to be secondary or less important. In fact, the most important build is now the OpenJDK one.

To be more specific, as of the release date, Java 11 developers should consider using jdk.java.net to obtain a binary download, not any page on oracle.com."

**Comment by sbondorf** [comment]
As I do not think it makes sense to have two different Java Implementations (Oracle and OpenJDK) for development and research, I switched to OpenJDK. Tests still run well. Not sure I'm glad to see that there is no adaptation of the pom.xml required as this can lead to the trap mentioned in the article linked by @paulnikolaus.
